language: generic

branches:
  only:
    - master

before_install:
  - nvm install

jobs:
  include:
    - name: JS unit tests
      before_install:
        - nvm install --latest-npm
      install:
        - npm ci
      script:
        - npm run test && eslint src
